#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        int1: '6789'
        ext1: '6789'
        image: 'linuxserver/nzbget'

    # CORE (MANDATORY) ############################################################
    - name: 'Mandatory Core Role'
      include_tasks: '/pg/apps/_core.yml'

    - name: 'Including folders'
      include_tasks: '/pg/apps/_downloaders.yml'

    - name: Create Folders
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=yes'
      with_items:
        - '{{path.stdout}}/nzb'
        - '{{path.stdout}}/{{pgrole}}/finished'
        - '{{path.stdout}}/{{pgrole}}/incomplete/tv'
        - '{{path.stdout}}/{{pgrole}}/finished/tv'
        - '{{path.stdout}}/{{pgrole}}/incomplete/movies'
        - '{{path.stdout}}/{{pgrole}}/finished/movies'
        - '{{path.stdout}}/{{pgrole}}/incomplete/movies4k'
        - '{{path.stdout}}/{{pgrole}}/finished/movies4k'
        - '{{path.stdout}}/{{pgrole}}/nzb'
        - '/pg/tmp'

    - name: 'Including plugins'
      include_tasks: '/pg/apps/_plugins.yml'

    - name: 'Checking for existing app data'
      stat:
        path: /pg/data/{{pgrole}}/nzbget.conf
      register: confcheck

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.port: '{{int1}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain}},{{tldset}}'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '/pg/data/{{pgrole}}:/config'
          - '{{path.stdout}}:{{path.stdout}}'
          - '/pg:/pg'
          - '/pg/tmp:/tmp'
          - '/mnt:/mnt'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          LC_ALL: 'C'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{serverports}}{{ext1}}:{{int1}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'

    # CONFIGURATION #############################################################
    - name: 'Waiting for {{pgrole}} to initialize'
      wait_for:
        path: '/pg/data/{{pgrole}}/nzbget.conf'
        state: present
        delay: 5

    - name: 'Stopping {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        state: stopped

    - name: Set Main Location
      lineinfile:
        path: '/pg/data/{{pgrole}}/nzbget.conf'
        regexp: '^MainDir\s*=.*'
        line: 'MainDir=/config'
        state: present

    - name: Set download location
      lineinfile:
        path: '/pg/data/{{pgrole}}/nzbget.conf'
        regexp: '^DestDir\s*=.*'
        line: 'DestDir={{path.stdout}}/{{pgrole}}/finished'
        state: present

    - name: Set incomplete location
      lineinfile:
        path: '/pg/data/{{pgrole}}/nzbget.conf'
        regexp: '^InterDir\s*=.*'
        line: 'InterDir={{path.stdout}}/{{pgrole}}/incomplete'
        state: present

    - name: Set TempDir
      lineinfile:
        path: '/pg/data/{{pgrole}}/nzbget.conf'
        regexp: '^TempDir\s*=.*'
        line: 'TempDir=/pg/tmp'
        state: present

    - name: Set NzbDir Location
      lineinfile:
        path: '/pg/data/{{pgrole}}/nzbget.conf'
        regexp: '^NzbDir\s*=.*'
        line: 'NzbDir={{path.stdout}}/{{pgrole}}/nzb'
        state: present

    - name: ScriptDir
      lineinfile:
        path: '/pg/data/{{pgrole}}/nzbget.conf'
        regexp: '^ScriptDir\s*=.*'
        line: 'ScriptDir=/pg/data/{{pgrole}}/scripts'
        state: present

    # FIRST TIME CONFIGURATION #############################################################
    - name: 'Configuring {{pgrole}} for first time use'
      block:
        - name: Lowercase & Set Movie Category
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '^Category1.Name\s*=.*'
            line: 'Category1.Name=movies'
            state: present

        - name: Set Location of Movies
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '^Category1.DestDir\s*=.*'
            line: 'Category1.DestDir='
            state: present

        - name: Lowercase & Set TV Category
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '^Category2.Name\s*=.*'
            line: 'Category2.Name=tv'
            state: present

        - name: Set Location of TV
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '^Category2.DestDir\s*=.*'
            line: 'Category2.DestDir='
            state: present

        - name: Lowercase & Set Music Category
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '^Category3.Name\s*=.*'
            line: 'Category3.Name=music'
            state: present

        - name: Set Location of Music
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '^Category3.DestDir\s*=.*'
            line: 'Category3.DestDir='
            state: present

        - name: Lowercase & Set EBook Category
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '^Category4.Name\s*=.*'
            line: 'Category4.Name=ebooks'
            state: present

        - name: Set Location of EBooks
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '^Category4.DestDir\s*=.*'
            line: 'Category4.DestDir='
            state: present

        - name: Lowercase & Set abook Category
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: 'Category5.Name\s*=.*'
            line: 'Category5.Name=abooks'
            state: present

        - name: Set Location of aBooks
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: 'Category5.DestDir\s*=.*'
            line: 'Category5.DestDir='
            state: present

        - name: Lowercase & Set Movie 4K Category
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '^Category6.Name\s*=.*'
            line: 'Category6.Name=movies4k'
            state: present

        - name: Set Location of Movies 4K
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '^Category6.DestDir\s*=.*'
            line: 'Category6.DestDir='
            state: present

        - name: Default User
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '^ControlUsername\s*=.*'
            line: 'ControlUsername='
            state: present

        - name: Default Password
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: 'ControlPassword\s*=.*'
            line: 'ControlPassword='
            state: present

        - name: DirectUnpack Set to On
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '^DirectUnpack\s*=.*'
            line: 'DirectUnpack=yes'
            state: present

        - name: HealthCheck
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '^HealthCheck\s*=.*'
            line: 'HealthCheck=Delete'
            state: present

        - name: Set DiskSpace
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '^DiskSpace\s*=.*'
            line: 'DiskSpace=25000'
            state: present

        - name: Remove Generic Task
          lineinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            regexp: '{{ item.regexp }}'
            state: absent
          with_items:
            - { regexp: '.Task1\.Time\=' }
            - { regexp: '.Task1\.WeekDays\=' }
            - { regexp: '.Task1\.Command\=' }
            - { regexp: '.Task1\.Param\=' }

        - name: Unpause
          blockinfile:
            path: '/pg/data/{{pgrole}}/nzbget.conf'
            block: |
              Task1.Time=*,*:00,*:30
              Task1.WeekDays=1-7
              Task1.Command=UnpauseDownload
              Task1.Param=
            insertafter: '^### SCHEDULER'
      when: not confcheck.stat.exists

    - name: Restart {{pgrole}}
      docker_container:
        name: '{{pgrole}}'
        state: started
